title: Nay Zaw Aung Win # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Mechanical Engineer by degree, Data Scientist by passion<br>
  Second description 
<<<<<<< HEAD
  <br>Welcome to my portfolio!<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
=======
  <br><br>
<<<<<<< HEAD
  <a href="https://www.linkedin.com/in/nay-zaw-aung-win-667973b1/">View My LinkedIn Profile</a> 
>>>>>>> 009c3e2d0c067dca382e1266df556aacecacc449
=======
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
>>>>>>> parent of 07581c2 (Added the link to my LinkedIn profile)
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
