title: <p style="color:black">Nay Zaw Aung Win</p> # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <em>Mechanical Engineer by degree, <br>Data Scientist by passion!</em> 
  <br><br>
  <a href="https://www.linkedin.com/in/nay-zaw-aung-win-667973b1/">View My LinkedIn Profile</a>
  
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
